I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 103, in script
    $ name = renpy.input("What is your name?", length=32, prompt="Name")
  File "game/script.rpy", line 103, in <module>
    $ name = renpy.input("What is your name?", length=32, prompt="Name")
TypeError: input() got multiple values for keyword argument 'prompt'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 103, in script
    $ name = renpy.input("What is your name?", length=32, prompt="Name")
  File "/Users/brandonnadell/Desktop/renpy-7.4.11-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "/Users/brandonnadell/Desktop/renpy-7.4.11-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 103, in <module>
    $ name = renpy.input("What is your name?", length=32, prompt="Name")
TypeError: input() got multiple values for keyword argument 'prompt'

Darwin-21.1.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
Writ 105CD Final Coded Artifact 1.0
Wed Mar  9 13:45:04 2022
