I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 137, in script
    with Fade(0.125)
TypeError: Fade() takes at least 3 arguments (3 given)

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 137, in script
    with Fade(0.125)
  File "C:\Users\Alex3\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 1443, in execute
    renpy.exports.with_statement(trans, paired)
  File "C:\Users\Alex3\Downloads\renpy-7.4.11-sdk/renpy/exports.py", line 1684, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\Alex3\Downloads\renpy-7.4.11-sdk/renpy/display/core.py", line 2762, in do_with
    clear=clear)
  File "C:\Users\Alex3\Downloads\renpy-7.4.11-sdk/renpy/display/core.py", line 3325, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs)
  File "C:\Users\Alex3\Downloads\renpy-7.4.11-sdk/renpy/display/core.py", line 3676, in interact_core
    new_widget=layers_root)
  File "C:\Users\Alex3\Downloads\renpy-7.4.11-sdk/renpy/curry.py", line 48, in __call__
    return self.callable(*(self.args + args), **merged_kwargs)
TypeError: Fade() takes at least 3 arguments (3 given)

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
final 1.0
Tue Mar  8 21:49:22 2022
