I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 115, in script
    me "Hey, I think we're roommates!"
Exception: Sayer 'me' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 115, in script
    me "Hey, I think we're roommates!"
  File "/Users/brandonnadell/Desktop/renpy-7.4.11-sdk/renpy/ast.py", line 681, in execute
    who = eval_who(self.who, self.who_fast)
  File "/Users/brandonnadell/Desktop/renpy-7.4.11-sdk/renpy/ast.py", line 574, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'me' is not defined.

Darwin-21.1.0-x86_64-i386-64bit
Ren'Py 7.4.11.2266
final 1.0
Wed Mar  2 14:33:49 2022
